file_format: "1"
id: ycorne
name: YpsilonCorne
type: shield
url: https://github.com/ypsilon-takai/zmk-config
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
siblings:
  - ycorne_left
  - ycorne_right
